# docker-compose.yaml
version: '3.3'
services:
  jenkins:
    image: jenkins/jenkins:lts
    container_name: my-jenkins
    ports:
      - 8099:8080
    restart: "always"
    volumes: 
      - /var/tmp/jenkins/:/var/jenkins_home
  
